
@ACCESS_JWT=eyJhbGciOiJSUzI1NiIsImtpZCI6IjVkNjE3N2E5Mjg2ZDI1Njg0NTI2OWEzMTM2ZDNmNjY0MjZhNGQ2NDIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29uZG8tbWdtdCIsImF1ZCI6ImNvbmRvLW1nbXQiLCJhdXRoX3RpbWUiOjE3MTUzMDcxNzUsInVzZXJfaWQiOiJZOGxSY2lqTzU2WWZicngxTTBlQkNaVWVzZm8yIiwic3ViIjoiWThsUmNpak81NllmYnJ4MU0wZUJDWlVlc2ZvMiIsImlhdCI6MTcxNjkxMTI3NCwiZXhwIjoxNzE2OTE0ODc0LCJlbWFpbCI6Im1zdG9ld3NAaG90bWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibXN0b2V3c0Bob3RtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.qIs8g-naw0S_G8LcYBOzYKof93ZKk1BonJSS4spu4Qgk4CFZaSoBy00X6I_DM0u9vsEvyzgDoBdY9Kv27M_wmCFBnNfDotbDnXtAZWHJVd1PnXeR1H6AuDlsjP8BQyJDJFX5ya5FN9ZCdAu1YWiuWEV11I3BZ4niTD7hyNcmBkLhZxYp2J4eH01lw3zFBDVuvbtgbLCxk1-5b6UQ6fTS_5-uPD87aGXdZq83plNQSjPIoBntUSuiJDJXx8chEwtsRDu3PlJee2jmFUvfxKgoIjw25bBPsLvGInB0AlYvhBQ-Pr1NGHAqpZC7sgtmgKu80ShuTWrUXdbNZpD8UBKhuQ

### GET("read_last_journal_no", server.ReadLastJournalNumber)
GET http://localhost:8080/v1/read_last_journal_no
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

### Create journal entry header
POST http://localhost:8080/v1/create_journal_header
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{	
"description": "Journal Ledger Description Test Entry",
"transaction_date": "2024-01-15",
"amount": 1000.00
}

### Create journal entry detail
POST http://localhost:8080/v1/create_journal_detail
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
"journal_id": 175,
"journal_subid": 1,
"account":1000,
"child":1001,
"description":"Accounts Receivable - Rev Received",
"create_date":"2024-02-12",	
"create_user":"mstoews@hotmail.com",
"sub_type":"Operating",
"debit":0.00,
"credit":1000.00,
"reference":"journal ID details 2 - reference",
"fund":"Reserve"
}


### Delete journal entry detail
POST http://localhost:8080/v1/delete_journal_details
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{    
"journal_id": 175,
"journal_subid": 1
}

### Read list of journals
GET http://localhost:8080/v1/read_journal_header
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

### Read list of journals_details
GET http://localhost:8080/v1/read_journal_detail
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}


### Update journal ledger header
POST http://localhost:8080/v1/update_journal_header
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{    
"journal_id": 175,	
"description": "Water Utilities Updated",
"transaction_date": "2024-05-15",
"amount": 150.00
}



### Get Journal Detail by ID
POST http://localhost:8080/v1/get_journal_detail/175
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{    
"journal_id": 175,	
}

### Update 


### Read a header by journal number
POST http://localhost:8080/v1/update_journal_detail
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
"journal_id": 175,
"journal_subid": 1,
"account":1000,
"child":1001,
"description":"Accounts Receivable - Rev Received",
"create_date":"2024-02-12",	
"create_user":"mstoews@hotmail.com",
"sub_type":"Operating",
"debit":0.00,
"credit":1000.00,
"reference":"journal ID details 2 - reference",
"fund":"Reserve"
}

