export interface IInvoice {
    invoice_id: number,
    invoice_no: string,
    invoice_date: Date,
    invoice_due_date: Date,
    invoice_amount: number,
    invoice_amount_paid: number,
    invoice_amount_due: number,
    invoice_status: string,
    invoice_description: string,
    invoice_reference: string,
    invoice_create_date: Date,
    invoice_create_user: string,
    invoice_update_date: Date,
    invoice_update_user: string,
    invoice_account: number,
    invoice_child: number,
    invoice_period: number,
}


export interface IVendors {
    vendor_id: number,
    vendor_name: string,
    vendor_type: string,
    vendor_status: string,
    vendor_address: string,
    vendor_city: string,
    vendor_state: string,
    vendor_zip: string,
    vendor_country: string,
    vendor_phone: string,
    vendor_fax: string,
    vendor_email: string,
    vendor_website: string,
    vendor_contact: string,
    vendor_contact_phone: string,
    vendor_contact_email: string,
    vendor_contact_fax: string,
    vendor_contact_cell: string,
    vendor_contact_title: string,
    vendor_contact_address: string,
    vendor_contact_city: string,
    vendor_contact_state: string,
    vendor_contact_zip: string,
    vendor_contact_country: string,
    vendor_contact_website: string,
    vendor_contact_notes: string,
    vendor_contact_status: string,
    vendor_contact_type: string,
    vendor_contact_id: number,
    vendor_contact_create_date: Date,
    vendor_contact_create_user: string,
    vendor_contact_update_date: Date,
    vendor_contact_update_user: string,
}




export interface IAPTransactions {
    transaction_id   : number,
    account          : number,
    child            : number,
    status           : string,
    ap_account       : number,
    ap_child         : number,
    period           : number,
    period_year      : number,
    transaction_date : Date,
    due_date         : Date,
    invoice_no       : string,
    payment          : number,
    order_no         : string,
    check_no         : string,
    reference        : string,
    description      : string,
    amount           : number,
    amount_paid      : number,
    date_paid        : Date,
    gst_amount       : number,
    pst_amount       : number,
    adjustment_amt   : number,
    rebate_amt       : number,
    remainder_amt    : number,
    create_date      : Date,
    create_user      : string,
    update_date      : Date,
    update_user      : string,
  }
